include ../Makefile.tests_common

# name of your application
APPLICATION = temperity

#module usage for library
USEMODULE += dht
USEMODULE += fmt
USEMODULE += xtimer

RIOTBASE ?= $(CURDIR)/../..

include $(RIOTBASE)/Makefile.include
